[ENH] ✨ The Add button should be more obvious
InseeFr/sugoi-ui pull request #363
Opened 2022-05-16 16:02 UTC by mehdimaaref7

2022-06-09 08:43 UTC, CChemin requested changes
You should not modify json files just for formatting purposes.
The button should be moved elsewhere in the component tree, not just moved with the style tag.

2022-07-04 12:48 UTC, Donatien26 commented
need rebase to be merge :)

2022-07-05 13:29 UTC, Donatien26 approved these changes

2022-07-05 13:30 UTC, Donatien26 approved these changes

2022-08-11 12:59 UTC, merged