[ENH] :sparkles: add global research
InseeFr/sugoi-ui pull request #373
Opened 2022-06-15 08:25 UTC by Donatien26

Signed-off-by: Donatien ENEMAN <donatien.eneman@insee.fr>

2022-06-23 13:56 UTC, mehdimaaref7 commented
Maybe we should abort the modifications on  `.eslintrc` file.

2022-07-07 08:34 UTC, CChemin requested changes
when you go from simple search to complex search and then return on simple search the field is disabled

2022-07-07 08:59 UTC, CChemin commented on src/components/shared/searchFormular/index.tsx
>  	userStorage?: string;
remove this

2022-07-07 09:01 UTC, CChemin commented on src/components/shared/searchFormular/index.tsx
>  	userStorage?: string;
and rename props to make sonar happy ^^

2022-07-08 11:47 UTC, CChemin commented on src/lib/hooks/organization/useGetOrganizations.tsx
> +		{ identifiant, mail, typeRecherche }: searchRequestOrganization,
why not getting the entire searchRequestOrganization and then pass the entire searchRequestOrganization

2022-08-17 09:48 UTC, CChemin approved these changes

2022-08-17 09:48 UTC, merged